//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ModelData
{
    using System;
    using System.Collections.Generic;
    
    public partial class Emp_Patient
    {
        public Emp_Patient()
        {
            this.Shed_Appoinment = new HashSet<Shed_Appoinment>();
        }
    
        public int Patient_Id { get; set; }
        public string Patient_Name { get; set; }
        public string Patient_address { get; set; }
        public Nullable<decimal> Patient_Pno { get; set; }
        public Nullable<int> App_Emp_Id { get; set; }
        public string Disease_type { get; set; }
    
        public virtual Emp_Employee Emp_Employee { get; set; }
        public virtual ICollection<Shed_Appoinment> Shed_Appoinment { get; set; }
    }
}
