//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ModelData
{
    using System;
    using System.Collections.Generic;
    
    public partial class Emp_Doc_Specialist
    {
        public Emp_Doc_Specialist()
        {
            this.Emp_Employee = new HashSet<Emp_Employee>();
        }
    
        public int Doc_specialist_id { get; set; }
        public string Doc_specialist { get; set; }
    
        public virtual ICollection<Emp_Employee> Emp_Employee { get; set; }
    }
}
