//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ModelData
{
    using System;
    using System.Collections.Generic;
    
    public partial class Emp_Employee
    {
        public Emp_Employee()
        {
            this.Emp_Patient = new HashSet<Emp_Patient>();
            this.Shed_Appoinment = new HashSet<Shed_Appoinment>();
            this.Shed_Available_Staff = new HashSet<Shed_Available_Staff>();
            this.User_Account = new HashSet<User_Account>();
        }
    
        public int Emp_id { get; set; }
        public string Emp_name { get; set; }
        public string Emp_callingName { get; set; }
        public string Emp_tiltie { get; set; }
        public Nullable<int> Emp_desig_id { get; set; }
        public Nullable<short> Emp_isActive { get; set; }
        public Nullable<int> UserGrpId { get; set; }
        public Nullable<int> Doc_specialist_id { get; set; }
    
        public virtual Emp_Designtion Emp_Designtion { get; set; }
        public virtual Emp_Doc_Specialist Emp_Doc_Specialist { get; set; }
        public virtual User_Group User_Group { get; set; }
        public virtual ICollection<Emp_Patient> Emp_Patient { get; set; }
        public virtual ICollection<Shed_Appoinment> Shed_Appoinment { get; set; }
        public virtual ICollection<Shed_Available_Staff> Shed_Available_Staff { get; set; }
        public virtual Shed_reshedule_Staff Shed_reshedule_Staff { get; set; }
        public virtual ICollection<User_Account> User_Account { get; set; }
    }
}
