//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ModelData
{
    using System;
    using System.Collections.Generic;
    
    public partial class Med_Details
    {
        public Med_Details()
        {
            this.Med_Prescription = new HashSet<Med_Prescription>();
        }
    
        public int Med_id { get; set; }
        public string Med_name { get; set; }
        public Nullable<int> Med_typeId { get; set; }
        public Nullable<decimal> Med_Available_quantity { get; set; }
    
        public virtual Med_Type Med_Type { get; set; }
        public virtual ICollection<Med_Prescription> Med_Prescription { get; set; }
    }
}
