//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ModelData
{
    using System;
    using System.Collections.Generic;
    
    public partial class Med_Type
    {
        public Med_Type()
        {
            this.Med_Details = new HashSet<Med_Details>();
        }
    
        public int MedTypeId { get; set; }
        public string MedType { get; set; }
        public Nullable<int> Med_quan_typeId { get; set; }
    
        public virtual ICollection<Med_Details> Med_Details { get; set; }
        public virtual Med_quantity_type Med_quantity_type { get; set; }
    }
}
