//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ModelData
{
    using System;
    using System.Collections.Generic;
    
    public partial class Med_ManualTime
    {
        public Med_ManualTime()
        {
            this.Med_Prescription = new HashSet<Med_Prescription>();
        }
    
        public int Med_manualTime_id { get; set; }
        public string Med_manualTime1 { get; set; }
    
        public virtual ICollection<Med_Prescription> Med_Prescription { get; set; }
    }
}
