//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ModelData
{
    using System;
    using System.Collections.Generic;
    
    public partial class Med_quantity_type
    {
        public Med_quantity_type()
        {
            this.Med_Type = new HashSet<Med_Type>();
        }
    
        public int Med_quan_typeId { get; set; }
        public string Med_quan_type { get; set; }
        public Nullable<decimal> Med_quantity { get; set; }
    
        public virtual ICollection<Med_Type> Med_Type { get; set; }
    }
}
