//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ModelData
{
    using System;
    using System.Collections.Generic;
    
    public partial class Med_Pres_type_Pres
    {
        public int Pres_type_pres_Id { get; set; }
        public int Pre_id { get; set; }
        public int Pres_Type_id { get; set; }
    
        public virtual Med_Pres_Type Med_Pres_Type { get; set; }
        public virtual Med_Prescription Med_Prescription { get; set; }
    }
}
