//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ModelData
{
    using System;
    using System.Collections.Generic;
    
    public partial class Shed_reshedule_Staff
    {
        public int Reshed_empId { get; set; }
        public Nullable<int> Emp_id { get; set; }
        public Nullable<System.DateTime> FromDate { get; set; }
        public Nullable<System.DateTime> ToDate { get; set; }
        public Nullable<decimal> FromTime { get; set; }
        public Nullable<decimal> ToTime { get; set; }
    
        public virtual Emp_Employee Emp_Employee { get; set; }
    }
}
