//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ModelData
{
    using System;
    using System.Collections.Generic;
    
    public partial class User_Group_Role
    {
        public User_Group_Role()
        {
            this.User_Account = new HashSet<User_Account>();
        }
    
        public int UserGrpRoleId { get; set; }
        public Nullable<int> UserGrpId { get; set; }
        public Nullable<int> UserRoelId { get; set; }
    
        public virtual ICollection<User_Account> User_Account { get; set; }
        public virtual User_Group User_Group { get; set; }
        public virtual User_Role User_Role { get; set; }
    }
}
