//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ModelData
{
    using System;
    using System.Collections.Generic;
    
    public partial class User_Role
    {
        public User_Role()
        {
            this.User_Group_Role = new HashSet<User_Group_Role>();
        }
    
        public int UserRoelId { get; set; }
        public string UserRole { get; set; }
    
        public virtual ICollection<User_Group_Role> User_Group_Role { get; set; }
    }
}
