//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ModelData
{
    using System;
    using System.Collections.Generic;
    
    public partial class User_Group
    {
        public User_Group()
        {
            this.Emp_Employee = new HashSet<Emp_Employee>();
            this.User_Group_Role = new HashSet<User_Group_Role>();
        }
    
        public int UserGrpId { get; set; }
        public string UserGroup { get; set; }
    
        public virtual ICollection<Emp_Employee> Emp_Employee { get; set; }
        public virtual ICollection<User_Group_Role> User_Group_Role { get; set; }
    }
}
